### ISSUE TITLE
Adding Participants

### ISSUE THREAD

**Issue by czgdp1807** [RoboticsClubIITJ/AdaBoost#1]
#### Description of the problem

This issue aims at obtaining comments from those who wish to participate in the project.
Any comment after 10th January, 2020 will not be considered. 
Just ping me in the comments to show your interest for participation.

The requirements of the project are as follows,

1. Give 15-20 hours per week.
2. Should be able to read papers related to AdaBoost and understand the mathematics. (Try https://en.wikipedia.org/wiki/AdaBoost or https://medium.com/machine-learning-101/https-medium-com-savanpatel-chapter-6-adaboost-classifier-b945f330af06 and if you can understand bits of it then you should be able to manage)
3. Aware of Object Oriented Programming in Python or C++.

#### References/Other comments
Those who have already joined the gitter chat room of the project before this issue was opened are a part of the team and their comments will not change that. Thanks.

**Comment by HardSavani** [comment]
@czgdp1807,  
I am interested in doing so.

**Comment by czgdp1807** [comment]
Thanks @HardSavani for the interest. 
Join [gitter chat room](https://gitter.im/Robotics-Club-IITJ/adaboost) and take a look at [plan of action](https://github.com/RoboticsClubIITJ/AdaBoost/wiki/Plan-of-Action).

**Comment by czgdp1807** [comment]
Closing as per the deadline set.
